import { SITE } from "./site";
import Visitors from "./Visitors";

export default function MkFooter() {
  return (
    <footer className="mk">
      <div className="mk-foot">
        <div className="mk-foot-top">
          <div className="mk-foot-brand">{SITE.name}</div>
          <div className="footer-links">
            <a href="/dashboard">Dashboard</a>
            <a href="/brief">Daily brief</a>
            <a href="/pricing">Pricing</a>
            <a href="/join">Join</a>
            <a href="/terms">Terms</a>
            <a href="/refund">Refunds</a>
            <a href="/privacy">Privacy</a>
            <a href="/contact">Contact</a>
            <a
              href={`https://wa.me/${SITE.phoneDigits}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              {SITE.phoneDisplay}
            </a>
          </div>
        </div>
        <p>
          {SITE.name} summarises public filings made with NSE and BSE. It is not
          investment advice, and we are not a SEBI-registered research analyst or
          investment adviser. Nothing here is a recommendation to buy or sell.
          Always read the original filing and take your own advice before acting.
        </p>
        <p>
          Summaries are generated by AI and can contain mistakes. Where our
          summary and the filing disagree, the filing is correct.
        </p>

        {/* Last thing on the page, bottom right, deliberately quiet. */}
        <Visitors />
      </div>
    </footer>
  );
}
