import { LEGAL } from "../../lib/legal";

export const metadata = { title: "Terms of Service — Market Tide" };

export default function Terms() {
  return (
    <div className="wrap legal">
      <a className="back" href="/">← Market Tide</a>
      <h1>Terms of Service</h1>
      <p className="updated">Last updated {LEGAL.updated}</p>

      <h2>1. Who we are</h2>
      <p>
        {LEGAL.brand} is operated by {LEGAL.entity}, {LEGAL.address}. You can
        reach us at {LEGAL.email} or {LEGAL.phoneDisplay}. In these terms
        &ldquo;we&rdquo; and &ldquo;us&rdquo; mean {LEGAL.brand}, and
        &ldquo;you&rdquo; means the person using the service.
      </p>

      <h2>2. What the service does</h2>
      <p>
        We collect corporate announcements that companies file with the National
        Stock Exchange and the Bombay Stock Exchange, filter out routine
        paperwork, and publish short summaries of the ones that matter, along
        with a link to the original filing.
      </p>
      <p>
        The underlying filings are public documents published by the exchanges.
        We do not own them and we do not claim to. Our summaries, scoring and
        categorisation are our own work.
      </p>

      <h2>3. This is not investment advice</h2>
      <p className="callout">
        {LEGAL.brand} is an information service. We are <strong>not</strong> a
        SEBI-registered Research Analyst or Investment Adviser. Nothing on this
        site is a recommendation to buy, sell or hold any security. We do not
        know your circumstances and we are not advising you.
      </p>
      <p>
        Any label we attach to a filing — including whether we mark it as
        Positive, Negative or Neutral — is a plain-language reading of the
        document, not a view on the share price. Always read the original filing
        and take your own advice before acting.
      </p>

      <h2>4. Summaries are generated by AI and can be wrong</h2>
      <p>
        Summaries are produced automatically by language models. They can
        misread a document, miss context, or state a number incorrectly. We link
        the original filing on every item precisely so you can check. Where our
        summary and the filing disagree, the filing is correct.
      </p>
      <p>
        We do not guarantee that the service captures every announcement, that
        it is available without interruption, or that it updates at any
        particular time. The exchanges can change their systems without notice.
      </p>

      <h2>5. Your account</h2>
      <p>
        A membership is for one person. Please do not share your login or
        redistribute our summaries as your own. We may end a membership without
        refund if it is shared or resold, or if you post buy-sell tips or
        promotional material in the community.
      </p>
      <p>
        Keep your login details to yourself. Tell us promptly at {LEGAL.email} if
        you think someone else has access to your account.
      </p>

      <h2>6. Payment</h2>
      <p>
        Each account may use one card-free seven-day Premium trial. It does not
        renew or turn into a charge. After the trial, Premium is ₹299 for three
        months, paid once in advance. Prices are in Indian rupees. Payments are
        handled by Cashfree; we never see or store your card details.
      </p>
      <p>
        We may change prices for future terms. A change never affects a term you
        have already paid for.
      </p>

      <h2>7. Cancelling and refunds</h2>
      <p>
        You may leave at any time. The three-month Premium fee is{" "}
        <strong>non-refundable</strong> once you have joined, except where you
        were charged twice, a payment succeeded but access was not provided, or
        we stop running the service during your paid term.
        Our <a href="/refund">Refund and Cancellation Policy</a> sets this out in
        full and forms part of these terms.
      </p>

      <h2>8. What we are responsible for</h2>
      <p>
        We provide the service in good faith and take reasonable care over it.
        To the extent the law allows, we are not liable for trading losses,
        missed opportunities, or decisions taken on the basis of anything you
        read here. Where liability cannot be excluded, it is limited to the
        amount you paid us for the current three-month term.
      </p>
      <p>Nothing here limits liability for fraud, or for anything the law says cannot be limited.</p>

      <h2>9. Ending the service</h2>
      <p>
        You can stop using {LEGAL.brand} at any time. We may suspend or close an
        account that breaches these terms, or withdraw the service entirely — if
        we withdraw it, we will refund the unused part of your subscription.
      </p>

      <h2>10. Changes to these terms</h2>
      <p>
        We may update these terms. If a change is significant we will tell
        subscribers by email or WhatsApp before it takes effect. The date at the
        top shows when this version was published.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These terms are governed by Indian law, and the courts of India have
        jurisdiction over any dispute.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these terms: <a href={`mailto:${LEGAL.email}`}>{LEGAL.email}</a>{" "}
        or WhatsApp {LEGAL.phoneDisplay}. See our <a href="/contact">contact page</a>.
      </p>
    </div>
  );
}
